### ISSUE TITLE
Enviar os feedbacks para monitores chefes e professores

### ISSUE THREAD

**Issue by rcrdrobson** [lucasbarross/gfip#10]
Quando um monitor realizar a avaliação da lista de seus alunos, o sistema deve poder enviar um relatorio para os monifores chefes e professores.

**Comment by rafaelmotaalves** [comment]
Tipo receber um relatório sobre todos os feedbacks enviados na lista?

**Comment by rcrdrobson** [comment]
Sim.
Descrevendo melhor o cenário:

Dado que o monitor responsavel por uma lista de alunos corrigiu as questões de seus alunos
Quando o monitor selecionar a feature "Enviar Relatorio para Superiores" (ou similar)
Então os monitores chefes receberão um relatório da coreção (isto é, um join dos feedbacks recebidos pelos alunos).

**Comment by rafaelmotaalves** [comment]
Então o monitor escolhe se vai pros superiores? Ou passa por eles antes dos alunos?

**Comment by rcrdrobson** [comment]
Creio que escolhe, sim.

Assim que corrige vai direto para os alunos, mas se escolhe se vai para os superiores (ou hj vai automaticamente?)

**Comment by rafaelmotaalves** [comment]
Hoje só vai pros alunos

**Comment by rafaelmotaalves** [comment]
Eu vou fechar a issue e quebrar em outras. Porque a gente não tem usuário administrador ainda. Tu vai querer implementar ou é só uma sugestão?

**Comment by rcrdrobson** [comment]
Certo.
É apenas uma sugestão.
